#!/usr/bin/env bash
# czytaj — Wireless ADB pairing setup (one-time).
# Configures Termux to talk to its own device's ADB daemon over localhost
# so we can call dumpsys window to detect screen unlock state.
# After this runs once, ~/.claude/czytaj-adb.flag is the sentinel that
# _speak.py reads to enable the unlock check.

set -e

FLAG="$HOME/.claude/czytaj-adb.flag"
# F36: keep the generated re-connect script OUT of the install-managed hook dir
# (install.sh treats that dir as a clean snapshot via an explicit allowlist).
CONNECT_SCRIPT="$HOME/.claude/czytaj-runtime/adb-connect.sh"
# F35/F44: pairing/connect logs → a private temp file (was world-readable /tmp,
# which is also not writable on the Termux-app target), removed on exit.
LOGDIR="${TMPDIR:-$HOME/.cache}"
mkdir -p "$LOGDIR" 2>/dev/null || true
PAIR_LOG="$(mktemp "$LOGDIR/adb-pair.XXXXXX.log")"
CONN_LOG="$(mktemp "$LOGDIR/adb-connect.XXXXXX.log")"
chmod 600 "$PAIR_LOG" "$CONN_LOG"
trap 'rm -f "$PAIR_LOG" "$CONN_LOG"' EXIT

echo ""
echo "==> czytaj — Wireless ADB pairing"
echo ""
echo "Ten skrypt łączy Termux z lokalnym ADB twojego telefonu, żeby"
echo "wykrywać czy ekran jest odblokowany (TTS milknie gdy zablokowany)."
echo ""

# --- Ensure adb binary present ---
if ! command -v adb >/dev/null 2>&1; then
  echo "  [!] BRAK: adb. Instaluję android-tools..."
  pkg install -y android-tools || {
    echo "  [X] Nie udało się zainstalować android-tools. Przerwane."
    exit 1
  }
fi
echo "  [OK] adb zainstalowane: $(adb --version | head -1)"
echo ""

# --- Reset existing adb server to avoid stale state ---
adb kill-server >/dev/null 2>&1 || true
adb start-server >/dev/null 2>&1

# --- Walk user through Wireless Debugging ---
cat <<'EOF'
KROK 1: Włącz Wireless Debugging
  - Settings → System → Developer options → Wireless debugging → ON
  - (Jeśli Developer options niewidoczne: Settings → About phone → tap
    "Build number" siedem razy.)

KROK 2: Otwórz "Pair device with pairing code"
  - Settings → System → Developer options → Wireless debugging
    → Pair device with pairing code
  - Zobaczysz: IP:PORT (np. 192.168.x.x:43251) i 6-cyfrowy kod
  - WAŻNE: zostaw ten ekran otwarty — kod znika po zamknięciu

EOF

read -r -p "Wpisz PORT z 'Pair device with pairing code' (np. 43251): " PAIR_PORT
PAIR_PORT="${PAIR_PORT//[^0-9]/}"
if [ -z "$PAIR_PORT" ]; then
  echo "  [X] Pusty port. Przerwane."
  exit 1
fi

read -r -p "Wpisz 6-cyfrowy kod: " PAIR_CODE
PAIR_CODE="${PAIR_CODE//[^0-9]/}"
if [ ${#PAIR_CODE} -ne 6 ]; then
  echo "  [X] Kod musi mieć 6 cyfr. Przerwane."
  exit 1
fi

echo ""
echo "Paruję z localhost:$PAIR_PORT ..."
if echo "$PAIR_CODE" | adb pair "localhost:$PAIR_PORT" 2>&1 | tee "$PAIR_LOG" | grep -q "Successfully paired"; then
  echo "  [OK] Pairing udany."
else
  echo "  [X] Pairing nieudany. Log:"
  cat "$PAIR_LOG"
  echo ""
  echo "  Najczęstsze przyczyny:"
  echo "  - Kod wygasł (otwórz okno pairing jeszcze raz, nowy kod)"
  echo "  - Inny PORT do connect niż do pairing (zwróć uwagę: są dwa porty)"
  echo "  - Wireless Debugging wyłączony"
  exit 1
fi

# --- Now ask for the CONNECT port (different from pair port) ---
echo ""
cat <<'EOF'
KROK 3: Connect port (różny od pair port!)
  W głównym widoku "Wireless debugging" widzisz "IP address & port":
    192.168.x.x:NNNNN
  TEN port wpisz teraz (NIE ten od pairing — pair port był jednorazowy
  i już wygasł).

EOF

read -r -p "Wpisz CONNECT PORT (z 'IP address & port'): " CONN_PORT
CONN_PORT="${CONN_PORT//[^0-9]/}"
if [ -z "$CONN_PORT" ]; then
  echo "  [X] Pusty port. Przerwane."
  exit 1
fi

echo ""
echo "Łączę z localhost:$CONN_PORT ..."
if adb connect "localhost:$CONN_PORT" 2>&1 | tee "$CONN_LOG" | grep -qE "connected|already connected"; then
  echo "  [OK] Connected."
else
  echo "  [X] Connect nieudany. Log:"
  cat "$CONN_LOG"
  exit 1
fi

# --- Smoke test ---
echo ""
echo "Test: czy adb shell działa?"
if SHELL_OUT=$(timeout 3 adb shell echo czytaj-ok 2>&1) && [ "$SHELL_OUT" = "czytaj-ok" ]; then
  echo "  [OK] adb shell działa."
else
  echo "  [X] adb shell NIE działa. Output:"
  echo "$SHELL_OUT"
  exit 1
fi

# --- Test: dumpsys window readable? ---
echo ""
echo "Test: czy dumpsys window dostępne (potrzebne do detekcji unlock)?"
if timeout 3 adb shell dumpsys window 2>/dev/null | head -5 | grep -q "WINDOW MANAGER"; then
  echo "  [OK] dumpsys window działa — pełna detekcja odblokowania możliwa."
else
  echo "  [!] dumpsys window niedostępne — spróbuję inny endpoint."
  if timeout 3 adb shell dumpsys power 2>/dev/null | grep -q "mWakefulness"; then
    echo "  [OK] dumpsys power działa — fallback aktywny."
  else
    echo "  [X] Żaden dumpsys nie działa. Coś nie tak z konfiguracją."
    exit 1
  fi
fi

# --- Persist connection script for re-connect after reboot ---
mkdir -p "$(dirname "$CONNECT_SCRIPT")"
cat > "$CONNECT_SCRIPT" <<EOF
#!/usr/bin/env bash
# Auto-generated by setup-adb-pairing.sh — re-connects ADB after reboot.
# Pairing survives reboot but connection does not.
adb connect "localhost:$CONN_PORT" >/dev/null 2>&1
EOF
chmod 700 "$CONNECT_SCRIPT"

# --- Sentinel flag: signal to _speak.py that unlock detection is enabled ---
echo "$CONN_PORT" > "$FLAG"
chmod 600 "$FLAG"

cat <<EOF

==> Gotowe. Konfiguracja zapisana:
  $FLAG          (sentinel + connect port)
  $CONNECT_SCRIPT  (re-connect po reboot)

Po każdym restarcie telefonu uruchom:
  bash $CONNECT_SCRIPT

(Albo dodaj to wywołanie do ~/.bashrc / Termux:Boot dla automatyki.)

Aby WYŁĄCZYĆ detekcję odblokowania:
  rm $FLAG

EOF
